### ISSUE TITLE
Should remove dependency on mailgun/log

### ISSUE THREAD

**Issue by serussell** [vulcand/vulcand#211] opened 2015-06-02 02:03 UTC
vbundle builds code that depends on mailgun/log, but mailgun/log can't seem to maintain a stable API; hence, the vulcand middleware tools are broken.  In particular, vctl main.go uses log.LogConfig, which has been removed from mailgun/log, so vctl can't be compiled.

Maybe switch to a more stable logging API?  In any case, mailgun/log's instability means vulcand is currently broken.

**Comment by philk** [comment] 2015-07-10 21:16
+1

We're currently just doing a stupid sed replacement on the generated `main.go` for `vctl` to replace the import with the `Godep/_workspace` import.

Would replacing [templates.go#L57](https://github.com/mailgun/vulcand/blob/master/vbundle/templates.go#L57) with `github.com/mailgun/vulcand/Godeps/_workspace/src/github.com/mailgun/log` be an acceptable fix @klizhentas ?

**Comment by klizhentas** [comment] 2015-07-10 22:50
@philk this will work

**Comment by pquerna** [comment] 2015-08-06 18:16
@klizhentas the `mailgun/log` API.... if thats the new API, should we just update vulcand? or do you want to switch to a different logging package?  The status quo is moderately annoying for us bundling vulcan services downstream.

**Comment by klizhentas** [comment] 2015-08-06 18:46
@pquerna @r0mant @jeremyschlatter I think we should revert the breaking change in the logging package in the first place. It's actually missing `Writer` method and `FanOut` logger that vulcand needs.

@r0mant can you please recover the deleted interfaces to make sure that after godep update vulcand works?

**Comment by r0mant** [comment] 2015-08-06 18:57
@klizhentas @pquerna @jeremyschlatter

We can't revert it because it introduces the new functionality (like, udplog support) that is used in production. Writer method is still there by the way. Basically, the external changes are trivial:

* LogConfig was renamed to Config.
* Init method signature changed.
* Fatalf method is gone.

Everything else is pretty much the same.

Also, I don't quite get why vulcand is not working if the old mailgun/log package is vendored? I can update vulcand to the latest mailgun/log, shouldn't be too hard.

**Comment by r0mant** [comment] 2015-08-06 19:00
Ah, I see that code generator uses just "github.com/mailgun/log". Looks like @pquerna has already submitted a pr to add stuff that prevents from upgrading vulcand to it.

**Comment by pquerna** [comment] 2015-08-06 19:01
I'll submit a PR to update vulcand.  working on it.

@r0mant the problem is when you use vulcanbundle (or any other method of embedding vulcand), and you'll end up with a newer version of mailgun/log.

**Comment by pquerna** [comment] 2015-08-06 19:17
fixed with #226

**Comment by horkhe** [comment] 2017-04-30 02:51
fixed with #329

**Closed by horkhe** 2017-04-30 02:51 UTC
Labels: enhancement
